[project]
name = "opensourcerepo"
version = "0.0.1"
description = ""
authors = [
    { name = "Name <Email>" }
]
license = { text = "MIT" }
requires-python = ">=3.10"

dependencies = [
    "agentstack[langgraph]>=0.3.5",
]